# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1383123901);
user_pref("app.update.lastUpdateTime.background-update-timer", 1383123781);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1383124021);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1383123542);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1383123661);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "C:\\Users\\Public\\Pictures\\Sample Pictures");
user_pref("browser.download.panel.firstSessionCompleted", true);
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 13);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.rights.3.shown", true);
user_pref("browser.slowStartup.averageTime", 3677);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20130814063812");
user_pref("browser.startup.homepage_override.mstone", "23.0.1");
user_pref("browser.taskbar.lastgroupid", "E7CF176E110C211B");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1383209941177");
user_pref("datareporting.healthreport.service.firstRun", true);
user_pref("datareporting.policy.firstRunTime", "1383123541177");
user_pref("datareporting.sessions.current.activeTicks", 116);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 2728);
user_pref("datareporting.sessions.current.main", 83);
user_pref("datareporting.sessions.current.sessionRestored", 3652);
user_pref("datareporting.sessions.current.startTime", "1383123540232");
user_pref("datareporting.sessions.current.totalTime", 1252);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:23.0.1");
user_pref("extensions.hotfix.certs.1.sha1Fingerprint", "91:53:98:0C:C1:86:DF:47:8F:35:22:9E:11:C9:A7:31:04:49:A1:AA");
user_pref("extensions.hotfix.lastVersion", "20130826.01");
user_pref("extensions.installCache", "[{\"name\":\"winreg-app-global\",\"addons\":{\"web2pdfextension@web2pdf.adobedotcom\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Adobe\\\\Acrobat 10.0\\\\Acrobat\\\\Browser\\\\WCFirefoxExtn\",\"mtime\":1345024515224,\"rdfTime\":1343422312000}}},{\"name\":\"app-global\",\"addons\":{\"afext@anchorfree.com\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\afext@anchorfree.com\",\"mtime\":1378126112400,\"rdfTime\":1377605877688},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"C:\\\\Program Files (x86)\\\\Mozilla Firefox\\\\browser\\\\extensions\\\\{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1378126118724,\"rdfTime\":1378126118705}}}]");
user_pref("extensions.lastAppVersion", "23.0.1");
user_pref("extensions.lastPlatformVersion", "23.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("gecko.buildID", "20130814063812");
user_pref("gecko.mstone", "23.0.1");
user_pref("gfx.direct3d.last_used_feature_level_idx", 0);
user_pref("intl.charsetmenu.browser.cache", "UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.database", "{\"files\":[{\"fingerprint\":\"6a7c2979f36c9144a770d7db6912e997\",\"exists\":true,\"page\":3,\"zoom\":\"auto\",\"scrollLeft\":0,\"scrollTop\":842}]}");
user_pref("pdfjs.migrationVersion", 1);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104439);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("toolkit.startup.last_success", 1383123540);
user_pref("toolkit.telemetry.previousBuildID", "20130814063812");
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1385715560);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
